### ISSUE TITLE
How to give fixed arguments for `map()`? 

### ISSUE THREAD

**Issue by Jylpah** [daniil-berg/asyncio-taskpool#1]
Hello, 

`asyncio-taskpool` seems an interesting project, but it seems there is no way to give fixed arguments for `map()`. I need to give an `Iterable[T]` and a set of fixed arguments to `map()`. Thus each spawned coroutine would get an element from `Iterable[T]` and the same fixed arguments.

Is this possible somehow? 

Cheers, 

Jylpah

**Comment by daniil-berg** [comment]
Hi. I am afraid I don't quite understand what you mean. Could you give an example of the coroutine function you want to use?

Do you mean given a function `async def f(x, y)` you want to spawn coroutines that all get the same argument for `x` but different arguments for `y`?

**Comment by Jylpah** [comment]
Hi, I met a case where the function is run with other parameters, but iteration happens only with one. I learned I can use `lambda` functions for that.

**Comment by daniil-berg** [comment]
Alright. Without seeing an example use case, I cannot say if `lambda` functions are a good idea in this context, but if it works for you I guess I can consider this issue closed.
